### ISSUE TITLE
TODO From Dec24

### ISSUE THREAD

**Issue by Cary-Xx** [llmhyy/evosuite_progress#132]
**TODOs**

- [x] Mutation issue: mutationChange() is fixed by truncating the statements after target method call, mutationInsert() needs to be amended by disallowing inserting after target.

- [x] Re-calculate time: If the method achieves the same coverage (e.g., 40%) (not 100%) for both strategies, we record the timestamp when the coverage first reaches 40%.

- [ ] Construct rough idea on how to construct objects: 

1. Global variable
2. Child class of interface or abstract class
3. Consecutive object assignments
4. Calling correct constructor ( if exists )
**Preliminary Goal :** Retrieving all relevant variables (including all) and their corresponding set places

- [x] Run trivial flag method such as _StringUtils.isNotEmpty(string)_ using new time recording rule and compare the performances
